import = [
    "~/.config/alacritty/themes/themes/thelovelace.toml"
]

[window]
blur = true
opacity = 0.7
option_as_alt = "Both" 
[font]

normal.family = "JetBrainsMono NF"
bold.family = "JetBrainsMono NF"
italic.family = "JetBrainsMono NF"
bold_italic.family = "JetBrainsMono NF"

size = 15.0
